name: Build and push to aws 

on:
push:
  branches:
    - main


    jobs:
      build:
        rons-on: ubuntu-latest
        
        steps:
          -name: checkout repo 
           uses:  actions/checkout@v3


          name:  setup dotnet  
          uses:  actions/setup-dotnet@v3
          white: 
             dotnet-version '6.0'

          -name: Bulid project
           run:  dotnet restore; dotnet publish o- site;
           -name: create zip package
          
            run:  cd site; zip ..site.zip *;

            -name: Deploy to aws EB
             uses:enaregilsson/beanstalk-deploy@21
             white:
                aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID}}
                aws_secret_key: ${{ secrets.AWS_SECRET
                application_name:calculetor API
                environment_name: calculetorAPI-env
                version_lanel:${{github.run_id }}
                region: eu-north-1
                deployment_package: site.zip